services:
  - type: web
    name: xml-crud
    env: go
    plan: free
    buildCommand: go build -o server .
    startCommand: ./server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: xml-crud-db
          property: connectionString

databases:
  - name: xml-crud-db
    plan: free
